### ISSUE TITLE
如何通过pandoc输出html中，也实现您的功能

### ISSUE THREAD

**Issue by jerecao** [i5ting/i5ting_ztree_toc#11]
1.我使用的sublime text结合markmon，通过pandoc输出html的。
（参见：http://blog.csdn.net/duqi_yc/article/details/8974041  《Markdown+Pandoc，打通写作界的任督二脉》
https://sublime.wbond.net/packages/Markmon%20real-time%20markdown%20preview
）
2.通过将您的js文件加载到pandoc的模板中，实现输出的html也包含您的js文件，但是不起作用，没有任何侧边栏出现。

我看你的文档中写的是tocmd生成html的，不知道是不是不支持通过pandoc输出。

附件是我生成的文档。http://pan.baidu.com/s/1gdu0JC3

在此非常感谢，佩服你做的产品。顺祝，工作顺利，身体健康

**Comment by i5ting** [comment]
结构不正确

```
    <div style='width:25%;'>
                                    <ul id="tree" class="ztree" style='width:100%'>

                                    </ul>
                            </div>
                    <div id='readme' style='width:70%;margin-left:20%;'>
                        <article class='markdown-body'>
                                            <h1 id="欢迎使用马克飞象"><span class="header-section-number">1</span> 欢迎使用马克飞象</h1>
                                                .....
                        </article>
                    </div>
                    </div>
```

这样就可以了，而且你的css和图片有问题，还是用直接生成的吧

**Comment by jerecao** [comment]
灰常灰常灰常灰常感谢，问题解决了。
